### ISSUE TITLE
Language packs are old

### ISSUE THREAD

**Issue by mahtiankka** [KaOSx/croeso#4] opened 2024-02-06 07:55 UTC
I have been translate the Kaos operating system for 8 months now. Croeso and Octopi haven't been updated all this time. Is there something wrong with Transifex synchronization? My translation is Finnish. The translation here is over a year old. Many others have more than 2 years.

**Comment by demmm** [comment] 2024-02-06 09:46
First of all, thanks for the translation work, really appreciated.

On transifex > Croeso, last change for Finnish shows as from March 2023, this was pulled into Croeso early April last year:
https://github.com/KaOSx/croeso/commit/5d07634c68e10b3d32268e62450b53f90f714085
Latest build from Croeso was last month, version 2.0, are you reporting for that version?

As for Octopi, that is not part of KaOS, but a standalone upstream project, translations are released with a new update here:
https://github.com/aarnt/octopi/

Is the translation in for example, Calamares correct?  That was also just updated for the last ISO (released last week).

**Comment by mahtiankka** [comment] 2024-02-06 13:58
Thank you for the quick reply

Some problem in controlling the Croeso language package. Croeso is always in English when I start the computer. It has not been seen in 2023 and the new Kaos 1_2024 also in English. If I copy the language pack it works.

Calamares + Kaos extra works in Finnish. I made a few fixes to it yesterday.

**Comment by demmm** [comment] 2024-02-06 14:45
There certainly is something wrong with the Finnish translation files in Croeso.
Run Croeso with `LANG=fr Croeso` (substitute fr with any of the languages, like de or nl), Croeso shows fully in French.  Trying the same for LANG=fi or FI_fi FI, Croeso always shows in English.
Already tried with adjusting the .ts file header & adding utf-8, recreated the needed qm file, all no go, still investigating what the issue is.

**Comment by demmm** [comment] 2024-02-06 15:18
Thanks for reporting, because of it, it was found that none of the new translations worked.

The Welcome app is now also corrected, same issue as commit above.

**Closed as completed** 2024-02-06 15:17 UTC
